title: Data Contribution Estimation for ML
description: Project page for the NeurIPS 2023 Data Contribution Estimation for Machine Learning Tutorial.
theme: just-the-docs

color_scheme: wider

url: https://www.stephanieschoch.com/neurips2023-dce-tutorial

aux_links:
  Tutorial: https://nips.cc/virtual/2023/tutorial/73959
